apiVersion: v1
kind: Secret
metadata:
  name: postgres-document-secret
  namespace: file-app
type: Opaque
data:
  password: cG9zdGdyZXM=

# get base64 encoding by the following command:
# echo -n <password> | base64

