name: Run Tests

on:
  pull_request:
    branches: [ "main", "app-fixes" ]
    paths:
      - 'frontend-user/**'
      - 'documents-service/**'
  push:
    branches: [ "main", "app-fixes" ]
    paths:
      - 'frontend-user/**'
      - 'documents-service/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests 
        run: |
          run_tests_if_exist() {
            if [ ! -d "$1/src/test" ]; then
              return 0
            fi
            
            if [ $(find "$1/src/test" -name "*Test.java" -type f 2>/dev/null | wc -l) -eq 0 ]; then
              return 0
            fi
            
            cd "$1"
            chmod +x mvnw 2>/dev/null || true
            ./mvnw test -DskipTests=false
          }
          
          run_tests_if_exist "frontend-user"
          run_tests_if_exist "documents-service"
