name: CI/CD Pipeline (Build, Push & Deploy)

on:
  workflow_dispatch:
    
  push:
    branches: [ "main" ]
    paths:
      - 'frontend-user/**'
      - 'documents-service/**'
      - '.github/workflows/full-cicd.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend-user/**'
      - 'documents-service/**'
      - '.github/workflows/full-cicd.yml'

env:
  REGISTRY: ghcr.io
  USERNAME: mihaelagavrilova04
  FRONTEND_IMAGE_NAME: frontend-user
  DOCUMENTS_IMAGE_NAME: documents-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Frontend Build
        working-directory: ./frontend-user
        run: chmod +x mvnw

      - name: Build Frontend with Maven
        working-directory: ./frontend-user
        run: ./mvnw clean package

      - name: Build Frontend Docker Image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }} -f frontend-user/Dockerfile frontend-user/

      - name: Setup Documents Service Build
        working-directory: ./documents-service
        run: chmod +x mvnw

      - name: Build Documents Service with Maven
        working-directory: ./documents-service
        run: ./mvnw clean package

      - name: Build Documents Docker Image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.DOCUMENTS_IMAGE_NAME }}:${{ github.sha }} -f documents-service/Dockerfile documents-service/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: mihaelagavrilova04
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.DOCUMENTS_IMAGE_NAME }}:${{ github.sha }}
