name: Build frontend-user microservice Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'frontend-user/src/**'
      - 'frontend-user/pom.xml'
      - 'frontend-user/Dockerfile'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Make mvnw executable
        working-directory: ./frontend-user
        run: chmod +x mvnw

      - name: Build with Maven
        working-directory: ./frontend-user
        run: ./mvnw clean package

      - name: Build Docker image
        working-directory: ./frontend-user
        run: docker build -t ghcr.io/mihaelagavrilova04/project-service:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: mihaelagavrilova04
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/mihaelagavrilova04/project-service:latest
